### ISSUE TITLE
CloudTrail stacktrace 

### ISSUE THREAD

**Issue by daugustus** [Graylog2/graylog-plugin-aws#117]
this is a fresh install of graylog on CentOS Linux release 7.5.1804

graylog-server-3.0.0-12.noarch
graylog-enterprise-plugins-3.0.0-12.noarch
graylog-integrations-plugins-3.0.0-12.noarch
graylog-3.0-repository-1-6.noarch

This error is appearing in the logs. Additionally, I cannot get CloudWatch or CloudTrail logs into Graylog. This appears to be a configuration error but I cannot seem to determine how/where/what to adjust. I have a *similar* configuration working fine in another AWS region. 

Any help appreciated!

`2019-03-05T16:03:56.752Z ERROR [CloudtrailSNSNotificationParser] Parsing exception.
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'CloudTrail': was expecting ('true', 'false' or 'null')
 at [Source: CloudTrail validation message.; line: 1, column: 11]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2839) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1903) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858) ~[graylog.jar:?]
	at org.graylog.aws.inputs.cloudtrail.notifications.CloudtrailSNSNotificationParser.parse(CloudtrailSNSNotificationParser.java:36) [graylog-plugin-aws-3.0.0.jar:?]
	at org.graylog.aws.inputs.cloudtrail.notifications.CloudtrailSQSClient.getNotifications(CloudtrailSQSClient.java:55) [graylog-plugin-aws-3.0.0.jar:?]
	at org.graylog.aws.inputs.cloudtrail.CloudTrailSubscriber.run(CloudTrailSubscriber.java:89) [graylog-plugin-aws-3.0.0.jar:?]`

**Comment by danotorrey** [comment]
Hi @daugustus 
Thanks for the information. This issue could be occurring if the Raw Message Delivery box is checked for the SQS subscription attributes. Could you please make sure this box is unchecked, and let us know if this resolves the issue?

Instructions for finding this checkbox are available at https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html

**Comment by danotorrey** [comment]
@daugustus I just wanted to check in to find out you were able to solve this. We're happy to take a further look if you need any more help.
