### ISSUE TITLE
AWS plugin v 1.2.0 needs dynamo DB access - not mentioned in documentation

### ISSUE THREAD

**Issue by pmsumner** [Graylog2/graylog-plugin-aws#19]
```
2016-10-31_08:33:41.17625 Caused by: com.amazonaws.AmazonServiceException: User: arn:aws:iam::************:user/graylog-cloudtrail is not authorized to perform: dynamodb:CreateTable on resource: arn:aws:dynamodb:eu-west-1:***********:table/graylog-aws-plugin (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: AccessDeniedException; Request ID: 2UPIJA2L0UE3OMFG40EFQEN4Q3VV4KQNSO5AEMVJF66Q9ASUAAJG)
2016-10-31_08:33:41.17657       at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1377) ~[?:?]
2016-10-31_08:33:41.17735       at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:923) ~[?:?]
2016-10-31_08:33:41.17780       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:701) ~[?:?]
2016-10-31_08:33:41.17877       at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:453) ~[?:?]
2016-10-31_08:33:41.17908       at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:415) ~[?:?]
2016-10-31_08:33:41.17998       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:364) ~[?:?]
2016-10-31_08:33:41.18041       at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2048) ~[?:?]
2016-10-31_08:33:41.18148       at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2018) ~[?:?]
2016-10-31_08:33:41.18188       at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.createTable(AmazonDynamoDBClient.java:878) ~[?:?]
2016-10-31_08:33:41.18272       at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:127) ~[?:?]
2016-10-31_08:33:41.18315       at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.initialize(KinesisClientLibLeaseCoordinator.java:227) ~[?:?]
2016-10-31_08:33:41.18418       at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:396) ~[?:?]
2016-10-31_08:33:41.18462       ... 7 more
```

After adding policy allowing dyanmodb.* on arn:* (which I really need to narrow down) to the user, the error messages stopped.

**Comment by lennartkoopmann** [comment]
This is weird. Thanks for the report! I'm looking into it.

**Comment by lennartkoopmann** [comment]
Thanks for spotting this. I added a note to the README in 3e406579c6d8774703fecc8c6e668ec0af44126d.
