### ISSUE TITLE
InstanceLookupTable throws errors when not running inside AWS

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog-plugin-aws#45]
The `InstanceLookupTable` refresh throws errors when not running inside an AWS environment. It should not run when disabled or the Graylog setup does not reside inside AWS.

```
2017-10-04 01:17:59,851 ERROR: org.graylog.aws.processors.instancelookup.InstanceLookupTable - Error when trying to refresh AWS instance lookup table in [us-east-1]
com.amazonaws.SdkClientException: Unable to execute HTTP request: ec2.us-east-1.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1068) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1034) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:13930) ~[aws-java-sdk-ec2-1.11.174.jar:?]
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:13906) ~[aws-java-sdk-ec2-1.11.174.jar:?]
	at com.amazonaws.services.ec2.AmazonEC2Client.executeDescribeNetworkInterfaces(AmazonEC2Client.java:7290) ~[aws-java-sdk-ec2-1.11.174.jar:?]
	at com.amazonaws.services.ec2.AmazonEC2Client.describeNetworkInterfaces(AmazonEC2Client.java:7266) ~[aws-java-sdk-ec2-1.11.174.jar:?]
	at com.amazonaws.services.ec2.AmazonEC2Client.describeNetworkInterfaces(AmazonEC2Client.java:7302) ~[aws-java-sdk-ec2-1.11.174.jar:?]
	at org.graylog.aws.processors.instancelookup.InstanceLookupTable.reload(InstanceLookupTable.java:68) [classes/:?]
	at org.graylog.aws.processors.instancelookup.AWSInstanceNameLookupProcessor$1.run(AWSInstanceNameLookupProcessor.java:82) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.net.UnknownHostException: ec2.us-east-1.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_144]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_144]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_144]
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[aws-java-sdk-core-1.11.174.jar:?]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.conn.$Proxy198.connect(Unknown Source) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar:4.5.3]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1189) ~[aws-java-sdk-core-1.11.174.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029) ~[aws-java-sdk-core-1.11.174.jar:?]
	... 20 more
```

**Comment by joschi** [comment]
@bernd Also see Graylog2/graylog-plugin-threatintel#55.

Looks like we should fix this in the lookup table/adapter interface in Graylog core.

**Comment by bernd** [comment]
@joschi The `InstanceLookupTable` is not using the lookup table infrastructure yet.

But can you elaborate on how to fix this in the interface? Adding a method to indicate if the lookup table should run/refresh?

**Comment by joschi** [comment]
> Adding a method to indicate if the lookup table should run/refresh?

Yes, for example by adding lifecycle methods similar to [`Service`](https://google.github.io/guava/releases/23.0/api/docs/com/google/common/util/concurrent/Service.html) which allow starting/stopping lookup tables (or their cache).

**Comment by bernd** [comment]
> Yes, for example by adding lifecycle methods similar to Service which allow starting/stopping lookup tables (or their cache).

The data adapters and caches are `AbstractIdleService` subclasses already. The problem is that they are currently started unconditionally. (and the refresh as well)

**Comment by joschi** [comment]
@bernd I'm unable to reproduce the issue if the "AWS Instance Name Lookup" processor is disabled or if "AWS Plugin Configuration" ➡️ "Instance detail lookups" is disabled.
