### ISSUE TITLE
Instance Lookup Failure

### ISSUE THREAD

**Issue by julian-berks** [Graylog2/graylog-plugin-aws#68]
Hi,
Set up the AWS plugin and given access to my AWS stack - I'm Getting
```text
2018-03-12T06:14:40.832-04:00 ERROR [AWSInstanceNameLookupProcessor] Could not refresh AWS instance lookup table.
java.lang.IllegalArgumentException: Multiple entries with same key: 172.16.130.9={AmiLaunchIndex: 0,ImageId: ami-bb9a6bc2,InstanceId: i-07a45d65b54e84037,InstanceType: t2.medium,KeyName: dbs-digital-Devops-Ireland-KeyPair,LaunchTime: Wed Sep 27 11:07:54 EDT 2017,Monitoring: {State: disabled},Placement: {AvailabilityZone: eu-west-1b,GroupName: ,Tenancy: default,},PrivateDnsName: ip-172-16-130-9.eu-west-1.compute.internal,PrivateIpAddress: 172.16.130.9,ProductCodes: [],PublicDnsName: ,State: {Code: 80,Name: stopped},StateTransitionReason: User initiated (2018-02-16 08:05:27 GMT),SubnetId: subnet-16e3e860,VpcId: vpc-c85206ac,Architecture: x86_64,BlockDeviceMappings: [{DeviceName: /dev/sda1,Ebs: {AttachTime: Wed Sep 27 11:07:54 EDT 2017,DeleteOnTermination: true,Status: attached,VolumeId: vol-0c01d32f3e3e7bf5a}}],ClientToken: dicZz1506524873505,EbsOptimized: false,EnaSupport: true,Hypervisor: xen,IamInstanceProfile: {Arn: arn:aws:iam::936943167675:instance-profile/ManagementS3ReadOnly,Id: AIPAJ6BPO32OFY5G4PJNM},ElasticGpuAssociations: [],NetworkInterfaces: [{Attachment: {AttachTime: Wed Sep 27 11:07:54 EDT 2017,AttachmentId: eni-attach-bb702bdc,DeleteOnTermination: true,DeviceIndex: 0,Status: attached},Description: Primary network interface,Groups: [{GroupName: CD Automation SG,GroupId: sg-42fa9724}],Ipv6Addresses: [],MacAddress: 06:82:89:ee:ff:1e,NetworkInterfaceId: eni-e48a9edb,OwnerId: 936943167675,PrivateDnsName: ip-172-16-130-9.eu-west-1.compute.internal,PrivateIpAddress: 172.16.130.9,PrivateIpAddresses: [{Primary: true,PrivateDnsName: ip-172-16-130-9.eu-west-1.compute.internal,PrivateIpAddress: 172.16.130.9}],SourceDestCheck: true,Status: in-use,SubnetId: subnet-16e3e860,VpcId: vpc-c85206ac}],RootDeviceName: /dev/sda1,RootDeviceType: ebs,SecurityGroups: [{GroupName: CD Automation SG,GroupId: sg-42fa9724}],SourceDestCheck: true,StateReason: {Code: Client.UserInitiatedShutdown,Message: Client.UserInitiatedShutdown: User initiated shutdown},Tags: [{Key: ANSIBLE_GROUP,Value: GITLAB}, {Key: Network,Value: DevOps - CD Automation (eu-west-1b)}, {Key: Environment,Value: Unknown}, {Key: Name,Value: Testing Gitlab Automation}, {Key: Project,Value: DBS_Digital}, {Key: ANSIBLE_ENVIRONMENT,Value: MANAGEMENT}],VirtualizationType: hvm} and 172.16.130.9={AmiLaunchIndex: 0,ImageId: ami-bb9a6bc2,InstanceId: i-07a45d65b54e84037,InstanceType: t2.medium,KeyName: dbs-digital-Devops-Ireland-KeyPair,LaunchTime: Wed Sep 27 11:07:54 EDT 2017,Monitoring: {State: disabled},Placement: {AvailabilityZone: eu-west-1b,GroupName: ,Tenancy: default,},PrivateDnsName: ip-172-16-130-9.eu-west-1.compute.internal,PrivateIpAddress: 172.16.130.9,ProductCodes: [],PublicDnsName: ,State: {Code: 80,Name: stopped},StateTransitionReason: User initiated (2018-02-16 08:05:27 GMT),SubnetId: subnet-16e3e860,VpcId: vpc-c85206ac,Architecture: x86_64,BlockDeviceMappings: [{DeviceName: /dev/sda1,Ebs: {AttachTime: Wed Sep 27 11:07:54 EDT 2017,DeleteOnTermination: true,Status: attached,VolumeId: vol-0c01d32f3e3e7bf5a}}],ClientToken: dicZz1506524873505,EbsOptimized: false,EnaSupport: true,Hypervisor: xen,IamInstanceProfile: {Arn: arn:aws:iam::936943167675:instance-profile/ManagementS3ReadOnly,Id: AIPAJ6BPO32OFY5G4PJNM},ElasticGpuAssociations: [],NetworkInterfaces: [{Attachment: {AttachTime: Wed Sep 27 11:07:54 EDT 2017,AttachmentId: eni-attach-bb702bdc,DeleteOnTermination: true,DeviceIndex: 0,Status: attached},Description: Primary network interface,Groups: [{GroupName: CD Automation SG,GroupId: sg-42fa9724}],Ipv6Addresses: [],MacAddress: 06:82:89:ee:ff:1e,NetworkInterfaceId: eni-e48a9edb,OwnerId: 936943167675,PrivateDnsName: ip-172-16-130-9.eu-west-1.compute.internal,PrivateIpAddress: 172.16.130.9,PrivateIpAddresses: [{Primary: true,PrivateDnsName: ip-172-16-130-9.eu-west-1.compute.internal,PrivateIpAddress: 172.16.130.9}],SourceDestCheck: true,Status: in-use,SubnetId: subnet-16e3e860,VpcId: vpc-c85206ac}],RootDeviceName: /dev/sda1,RootDeviceType: ebs,SecurityGroups: [{GroupName: CD Automation SG,GroupId: sg-42fa9724}],SourceDestCheck: true,StateReason: {Code: Client.UserInitiatedShutdown,Message: Client.UserInitiatedShutdown: User initiated shutdown},Tags: [{Key: ANSIBLE_GROUP,Value: GITLAB}, {Key: Network,Value: DevOps - CD Automation (eu-west-1b)}, {Key: Environment,Value: Unknown}, {Key: Name,Value: Testing Gitlab Automation}, {Key: Project,Value: DBS_Digital}, {Key: ANSIBLE_ENVIRONMENT,Value: MANAGEMENT}],VirtualizationType: hvm}
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:190) ~[graylog.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:109) ~[graylog.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:373) ~[graylog.jar:?]
	at org.graylog.aws.processors.instancelookup.InstanceLookupTable.reload(InstanceLookupTable.java:115) ~[graylog-plugin-aws-2.4.3.jar:?]
	at org.graylog.aws.processors.instancelookup.AWSInstanceNameLookupProcessor$1.run(AWSInstanceNameLookupProcessor.java:82) [graylog-plugin-aws-2.4.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```
The output implies it's found the same host twice (identical details) - how do I work around this?

**Comment by danocodes** [comment]
Are you still able to reproduce this error? Does the error always occur for you, or does it only occur with a specific AWS instance/network configuration? We are looking for any information that might help us identify why it is occurring in this case. Any additional info would be appreciated.

**Comment by danotorrey** [comment]
@julian-berks Are you still able to reproduce this error? Does the error always occur for you, or does it only occur with a specific AWS instance/network configuration? We are looking for any information that might help us identify why it is occurring in this case. Any additional info would be appreciated.

**Comment by danotorrey** [comment]
Hi @julian-berks, 
Since we have not heard back from you, we are closing this issue for now. If the error is still reproducible, please let us know, and we happy to investigate further.
