### ISSUE TITLE
Doesn't appear to be working on 2.0

### ISSUE THREAD

**Issue by evanccnyc** [Graylog2/graylog-plugin-aws#9]
I added the plugin to our new graylog 2.0 server but it never receives messages. The amazon side is exactly the same as before and the configuration was copied from the old 1.2 server.

Nothing in the log files, it just never receives any messages. Let me know what I can do to help track this down.

**Comment by STRML** [comment]
Works fine here once I merged #6 and the latest from master , but it did take a little time for it to start receiving messages. 

I've released this and my changes in #10 [here](https://github.com/BitMEX/graylog-plugin-aws/releases/tag/0.5.1).

**Comment by jskirst** [comment]
hey @STRML we're having this same issue, but using your plugin version. We're not seeing any errors or feedback that say that there's no messages coming. Any advice?

We're running
graylog AMI: ami-1b2aea76
graylog-plugin-aws: 0.5.1

**Comment by STRML** [comment]
Hmm. Have you checked all the logfiles on disk? I saw a few errors on my setup when IAM roles weren't set up right.

**Comment by jskirst** [comment]
Where are these logs stored? We've looked through every log directory we can and can't find anywhere posting those logs. All we can find are the nginx logs.

**Comment by STRML** [comment]
It shows up in the graylog logfile.

**Comment by STRML** [comment]
`/var/log/graylog-server/server.log`. If you don't have it, check your `/etc/graylog/server/log4j2.xml`.

**Comment by jskirst** [comment]
Thanks for your help @STRML! Really appreciate it. Unfortunately we don't seem to have either file. We used the AMI listed in https://github.com/Graylog2/graylog2-images/tree/2.0/aws, so not sure what we might have done wrong here.

**Comment by joschi** [comment]
@jskirst You can find the log files in the virtual machine images under `/var/log/graylog/server/*`.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by stepkirk** [comment]
I run Graylog under VMware using the supplied OVA.  After performing the Graylog 1.3.4 -> Graylog 2.0.2 upgrade, I still continued to receive CloudTrail logs from AWS using the official 0.5.0 plugin.  I upgraded to Graylog 2.0.3 on 6/20 and have not been able to receive CloudTrail logs since then.

This is what I see in /var/log/graylog/server/current when I try to (re)start the AWS CloudTrail input:

`2016-07-06_17:42:48.22191 2016-07-06 11:42:48,221 INFO : org.graylog2.inputs.InputStateListener - Input [AWS CloudTrail/56257090e4b084a9b8ca77b6] is now STARTING
2016-07-06_17:42:48.22355 2016-07-06 11:42:48,221 INFO : com.graylog2.input.cloudtrail.CloudTrailTransport - Starting cloud trail subscriber
2016-07-06_17:42:48.29081 2016-07-06 11:42:48,290 INFO : org.graylog2.inputs.InputStateListener - Input [AWS CloudTrail/56257090e4b084a9b8ca77b6] is now RUNNING
2016-07-06_17:42:48.75486 Exception in thread "Thread-15" java.lang.NoSuchMethodError: org.apache.http.params.HttpConnectionParams.setSoKeepalive(Lorg/apache/http/params/HttpParams;Z)V
2016-07-06_17:42:48.75565       at com.amazonaws.http.HttpClientFactory.createHttpClient(HttpClientFactory.java:96)
2016-07-06_17:42:48.75647       at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:187)
2016-07-06_17:42:48.75813       at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:136)
2016-07-06_17:42:48.75926       at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:120)
2016-07-06_17:42:48.76283       at com.amazonaws.services.sqs.AmazonSQSClient.<init>(AmazonSQSClient.java:200)
2016-07-06_17:42:48.76449       at com.amazonaws.services.sqs.AmazonSQSClient.<init>(AmazonSQSClient.java:180)
2016-07-06_17:42:48.76452       at com.graylog2.input.cloudtrail.notifications.CloudtrailSQSClient.<init>(CloudtrailSQSClient.java:27)
2016-07-06_17:42:48.76515       at com.graylog2.input.cloudtrail.CloudTrailSubscriber.run(CloudTrailSubscriber.java:59)`

I see the same error when I try the 0.5.1 version of the AWS plugin linked above.

Any thoughts on a possible fix?  Maybe I should post this on the mailing list instead?

Thanks.

**Comment by joschi** [comment]
Please check if the latest release of this plugin fixes your issues: https://github.com/Graylog2/graylog-plugin-aws/releases/tag/0.6.0

It's working for me on Graylog 2.0.0 and higher.

**Comment by stepkirk** [comment]
Thanks @joschi. The 0.6.0 version of the plugin is working for me.  Just took a bit to drain the backlog of messages. ;-)

**Comment by joschi** [comment]
@stepkirk Thanks for your feedback!

I'm closing this issue now. Feel free to leave a comment or open a new issue if the latest version of the plugin doesn't work for you.

**Comment by 123dev** [comment]
I switched to 0.6.0 and am getting this error
```
2016-07-08 15:35:36,138 INFO : org.graylog2.inputs.InputStateListener - Input [AWS CloudTrail Input/5728fea5f5f47c19bc14a86c] is now RUNNING
Exception in thread "Thread-14" java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.http.conn.ssl.SdkTLSSocketFactory
        at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:87)
        at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65)
        at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58)
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:50)
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
        at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:259)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:145)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:136)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:121)
        at com.amazonaws.services.sqs.AmazonSQSClient.<init>(AmazonSQSClient.java:229)
        at com.amazonaws.services.sqs.AmazonSQSClient.<init>(AmazonSQSClient.java:209)
        at com.graylog2.input.cloudtrail.notifications.CloudtrailSQSClient.<init>(CloudtrailSQSClient.java:39)
        at com.graylog2.input.cloudtrail.CloudTrailSubscriber.run(CloudTrailSubscriber.java:63)
```

Before that n 0.5.1 Snapshot it was working fine.
By the way at first when I first switched to 0.6.0 the plugin wouldn't start
I got this error
```
2016-07-07 16:31:24,940 ERROR: org.graylog2.shared.inputs.InputLauncher - The [com.graylog2.input.AWSInput] input with ID <5728fea5f5f47c19bc14a86c> misfired. Reason: Mandatory configuration field aws_sqs_region is missing.
org.graylog2.plugin.configuration.ConfigurationException: Mandatory configuration field aws_sqs_region is missing
        at org.graylog2.plugin.configuration.ConfigurationRequest.check(ConfigurationRequest.java:97) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.MessageInput.checkConfiguration(MessageInput.java:145) ~[graylog.jar:?]
        at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:82) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```
Then I edited the input set the region and saved
That got the plugin starting again, but with the exception above, I haven't seen any aws logs.

Thanks
